### PR TITLE
[SPARK-52070] Fix `Swift 6.0` compilation error

### PR DESCRIPTION
**Pull request by williamhyun**
### What changes were proposed in this pull request?
This PR aims to fix the build for Swift 6.0.

### Why are the changes needed?
Currently, the build on Swift 6.0 is broken due to a syntax error. 
- https://swiftpackageindex.com/apache/spark-connect-swift/builds

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Pass the CIs.

### Was this patch authored or co-authored using generative AI tooling?
No.

### CODE REVIEW

**Review by dongjoon-hyun — APPROVED** [review]
+1, LGTM. Thank you for making a PR to fix this, @williamhyun .

**Review by viirya — APPROVED** [review]

**Comment by dongjoon-hyun** [comment]
I verified this manually.
```
$ swift --version
Apple Swift version 6.0.3 (swift-6.0.3-RELEASE)
Target: arm64-apple-macosx15.0

$ swift build
Building for debugging...
[11/11] Emitting module SparkConnect
Build complete! (4.86s)
```

**Comment by dongjoon-hyun** [comment]
Merged to main.
